# Lifesteal SMP Configuration

# Starting hearts when player joins for the first time
starting-hearts: 10

# Maximum number of hearts a player can have (each heart = 2 HP)
max-hearts: 40

# If true, players lose 1 heart on non-player-caused deaths (environment, mobs, etc.)
death-penalty-enabled: true

# Material used for the heart item given from /withdrawheart
heart-item-material: NETHER_STAR

# MySQL database support
mysql:
  enabled: false
  host: localhost
  port: 3306
  database: lifestealsmp
  username: root
  password: ""

# Language file selection (lang_en.yml, lang_de.yml, etc.)
languages: en

# Custom crafting for heart item
heart-crafting:
  enabled: true
  recipe:
    shape:
      - "BEB"
      - "GNG"
      - "BSB"
    ingredients:
      B: NETHERITE_BLOCK
      E: ECHO_SHARD
      G: ENCHANTED_GOLDEN_APPLE
      N: NETHER_STAR
      S: HEART_OF_THE_SEA

# Custom crafting for revive beacon (fully configurable)
revive-beacon-crafting:
  enabled: true
  recipe:
    shape:
      - "NGN"
      - "SJS"
      - "NTN"
    ingredients:
      N: NETHERITE_BLOCK
      G: ENCHANTED_GOLDEN_APPLE
      S: WITHER_SKELETON_SKULL
      T: TOTEM_OF_UNDYING
      J: NETHER_STAR

# Display Messages (prefixes, ban, permissions, etc.)
messages:
  prefix: "&c&lLifesteal &7» "
  ban-message: "&cYou have run out of hearts!"
  withdraw-success: "&aYou withdrew 1 heart!"
  reload-success: "&aConfiguration reloaded!"
  no-permission: "&cYou do not have permission!"
