# ================================
# Lifesteal SMP - Configuration
# ================================

# Starting hearts a player has on first join (1 heart = 2 HP)
starting-hearts: 10

# Maximum hearts a player can accumulate
max-hearts: 40

# If true, players lose 1 heart on death by non-player causes (e.g., mobs, lava)
death-penalty-enabled: true

# Item type given when withdrawing a heart (/withdrawheart)
heart-item-material: NETHER_STAR

# MySQL Database Settings (used if enabled = true)
mysql:
  enabled: false
  host: localhost
  port: 3306
  database: lifestealsmp
  username: root
  password: ""

# Language configuration
# Files must exist in /plugins/LifestealSMP/lang/
languages: en

# Toggle detailed debug messages in console (for testing)
debug: false

# ----------------------------------
# Custom Crafting - Heart Item
# ----------------------------------
heart-crafting:
  enabled: true
  recipe:
    shape:
      - "BEB"
      - "GNG"
      - "BSB"
    ingredients:
      B: NETHERITE_BLOCK
      E: ECHO_SHARD
      G: ENCHANTED_GOLDEN_APPLE
      N: NETHER_STAR
      S: HEART_OF_THE_SEA

# ----------------------------------
# Custom Crafting - Revive Beacon
# ----------------------------------
revive-beacon-crafting:
  enabled: true
  recipe:
    shape:
      - "NGN"
      - "SJS"
      - "NTN"
    ingredients:
      N: NETHERITE_BLOCK
      G: ENCHANTED_GOLDEN_APPLE
      S: WITHER_SKELETON_SKULL
      T: TOTEM_OF_UNDYING
      J: NETHER_STAR

# ----------------------------------
# Custom Plugin Messages
# ----------------------------------
messages:
  prefix: "&c&lLifesteal &7» "
  ban-message: "&cYou have run out of hearts!"
  withdraw-success: "&aYou withdrew 1 heart!"
  reload-success: "&aConfiguration reloaded!"
  no-permission: "&cYou do not have permission!"
